### PR TITLE
Fix issue where using the same object causes issues with Build optimisers

### PR DESCRIPTION
**Pull request by tanepiper**
The existing code does not work with Angular, and possibly other Webpack bundlers where they optimize code.

The issue is that this code gets generated:

```
key: 'normalizeData', value: function(t) {
  return 'object' !== r(t) && (t = {}), t.text = t.text || '', t.level = parseInt(t.level) || this.defaultLevel.number, t;
}
```

When running this, `t`'s existing properties are readonly so it cannot overwrite them, this patch fixes it.

### CODE REVIEW

**Comment by tanepiper** [comment]
Hi @talyguryn @gohabereg sorry to ping you, but this PR has been open for two weeks.

Would it be possible to merge this change?  In my code to fix this, I extend the class but it's currently breaking my tests and this quick fix would resolve that.

Thanks

**Comment by gohabereg** [comment]
Hi @tanepiper ,
Sorry for delay! Fix is ok, could you please patch the version, build the package using `yarn build` and include build files to PR.

Thanks!

**Comment by tanepiper** [comment]
@gohabereg No problem, done.

**Comment by gohabereg** [comment]
There are conflicting files, I guess you need to pull the master and rebuild the package

**Pull request merged**
